/**
 * Supabase Configuration
 *
 * This file uses environment variables or falls back to existing credentials.
 * Priority:
 * 1. Environment variables (VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY)
 * 2. Fallback to existing autogenerated credentials
 */

// Existing autogenerated credentials (from info.tsx)
const FALLBACK_PROJECT_ID = "beswluhdxaphtitaovly";
const FALLBACK_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlc3dsdWhkeGFwaHRpdGFvdmx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4MDY2MzgsImV4cCI6MjA5MjM4MjYzOH0.XMxin_yjhgp3si6G_PFAWdrsaBzdJgfJcgyc-NQEXhw";

// Try to get from environment variables first
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Extract project ID from URL or use fallback
export const projectId = supabaseUrl
  ? supabaseUrl.replace('https://', '').replace('.supabase.co', '')
  : FALLBACK_PROJECT_ID;

export const publicAnonKey = supabaseAnonKey || FALLBACK_ANON_KEY;

// Log configuration status (dev only)
if (import.meta.env.DEV) {
  if (supabaseUrl && supabaseAnonKey) {
    console.log('✅ Supabase configured from environment:', projectId);
  } else {
    console.log('✅ Supabase using fallback credentials:', projectId);
  }
}
